//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Стройматериалы.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.UserOfOrderOfProduct = new HashSet<UserOfOrderOfProduct>();
            this.User1 = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public int Number { get; set; }
        public string Composition { get; set; }
        public System.DateTime DateOrder { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public Nullable<int> PointOfIssueID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Code { get; set; }
        public string Status { get; set; }
    
        public virtual PointOfIssue PointOfIssue { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserOfOrderOfProduct> UserOfOrderOfProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User1 { get; set; }
    }
}
