//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Стройматериалы.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.UserOfOrderOfProduct = new HashSet<UserOfOrderOfProduct>();
        }
    
        public int ID { get; set; }
        public string ArticleNumber { get; set; }
        public string Name { get; set; }
        public string UnitOfMeasurement { get; set; }
        public int Cost { get; set; }
        public int DiscountAmount { get; set; }
        public string Manufacturer { get; set; }
        public string Supplier { get; set; }
        public string Category { get; set; }
        public int CurrentDiscount { get; set; }
        public int QuantityInStock { get; set; }
        public string Description { get; set; }
        public byte[] Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserOfOrderOfProduct> UserOfOrderOfProduct { get; set; }
    }
}
